
services:
    mariadb:
        container_name: mariadb
        image: mariadb:v1
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped
        expose:
            - "3306"
        secrets:
            - db_password
            - db_root_password

    nginx:
        container_name: nginx
        image: nginx:v1
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - wordpress:/var/www/wordpress
            - ssl_certs:/etc/nginx/ssl
        restart: unless-stopped
        depends_on:
            - wordpress
        ports:
            - "443:443"

    wordpress:
        container_name: wordpress
        image: wordpress:v1
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - wordpress:/var/www/wordpress
        restart: unless-stopped
        depends_on:
            - mariadb
        expose:
            - "9000"
        secrets:
            - credentials

    redis:
        container_name: redis
        image: redis:v1
        build:
            context: requirements/bonus/redis
            dockerfile: Dockerfile
        networks:
            - inception
        env_file:
            - .env
        restart: unless-stopped

    adminer:
        container_name: adminer
        image: adminer:v1
        build:
            context: requirements/bonus/adminer
            dockerfile: Dockerfile
        networks:
            - inception
        restart: unless-stopped

    ftp:
        container_name: ftp
        image: ftp:v1
        build:
            context: requirements/bonus/ftp
            dockerfile: Dockerfile
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - inception
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - "21:21"
            - "40000-40005:40000-40005"
        secrets:
            - credentials

    static_site:
        container_name: static_site
        image: static_site:v1
        build:
            context: requirements/bonus/static_site
            dockerfile: Dockerfile
        volumes:
            - ssl_certs:/etc/nginx/ssl
            - static_site:/var/www/static
        networks:
            - inception
        restart: unless-stopped
        depends_on:
            - nginx
        ports:
            - "8081:8081"

    glances:
        container_name: glances
        image: glances:v1
        build:
            context: requirements/bonus/glances
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
          - inception
        expose:
          - "61208"

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/crappo/data/wordpress'

    mariadb:
        driver: local
        driver_opts:
            type: 'none' 
            o: 'bind'
            device: '/home/crappo/data/mariadb'

    ssl_certs:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/crappo/data/ssl'

    static_site:
        driver: local
        driver_opts:
            type: 'none' 
            o: 'bind'
            device: './requirements/bonus/static_site/tools'

networks:
    inception:
        driver: bridge

secrets:
    db_password:
        file: ../secrets/db_password.txt

    db_root_password:
        file: ../secrets/db_root_password.txt

    credentials:
        file: ../secrets/credentials.txt
